"""Regenerate ``services/openscript/openscript/stdlib_src.py`` from the engine's
``stdlib/*.os`` modules.

WHY THE EMBEDDING IS A ``.py`` MODULE AND NOT COPIED ``.os`` DATA FILES, which is
the load-bearing choice here: ``compiler_service._compiler_fingerprint()`` hashes
``package.rglob("*.py")``. Embedding the standard library as Python source means
any change to a primitive's body moves ``COMPILER_FINGERPRINT`` automatically and
rides the staleness refresh that already exists. Committed ``.os`` copies would
sit OUTSIDE that hash -- a stored indicator would keep executing IR built by a
compiler that no longer exists, silently, which is exactly the hole the
fingerprint was added to close.

The engine's ``stdlib/*.os`` stays authoritative. This script is a dev-time step;
``test_openscript_stdlib_drift.py`` byte-compares the committed result against the
sibling engine checkout on every CI run, so a stale embedding fails loudly rather
than diverging.

Run from the platform repo root, with the engine checked out beside it:

    uv run python scripts/gen_openscript_stdlib.py
"""

from __future__ import annotations

import sys
from pathlib import Path

# Must match tools/gen-stdlib.mjs MANIFEST exactly -- registration order is part
# of the contract (a module may reference only modules before it).
MANIFEST = ["candle", "fvg", "ob", "rjb", "pivot", "bos"]

ENGINE_STDLIB = Path(__file__).resolve().parents[1].parent / "openalgo-openscript" / "stdlib"
TARGET = Path(__file__).resolve().parents[1] / "services" / "openscript" / "openscript" / "stdlib_src.py"

HEADER = '''"""GENERATED by scripts/gen_openscript_stdlib.py -- do not edit.

Source of truth: the engine repo's ``stdlib/*.os``. Regenerate with
``uv run python scripts/gen_openscript_stdlib.py``;
``test_openscript_stdlib_drift.py`` fails if this file drifts from those sources.

This module is deliberately ``.py`` rather than copied data files so that a
stdlib body change moves ``COMPILER_FINGERPRINT`` -- see the generator's docstring.
"""

from __future__ import annotations

# (name, source) in registration order.
STDLIB_MODULES: tuple[tuple[str, str], ...] = (
'''


def normalize(raw: str, name: str) -> str:
    """The one normalization, mirroring ``tools/gen-stdlib.mjs``.

    Line endings are normalized because an ``autocrlf`` checkout would otherwise
    make the embedding differ from the source on Windows and match on Linux -- a
    drift guard that fails per-machine is worse than no guard at all.
    """
    text = raw.lstrip("﻿").replace("\r\n", "\n")
    if not text.strip():
        raise SystemExit(f"stdlib module '{name}' is empty")
    if not text.endswith("\n"):
        text += "\n"
    return text


def read_modules() -> list[tuple[str, str]]:
    if not ENGINE_STDLIB.is_dir():
        raise SystemExit(f"engine stdlib not found at {ENGINE_STDLIB}; check the sibling checkout")
    out = []
    for name in MANIFEST:
        path = ENGINE_STDLIB / f"{name}.os"
        if not path.is_file():
            raise SystemExit(f"missing stdlib module: {path}")
        out.append((name, normalize(path.read_text(encoding="utf-8"), name)))
    return out


def render(modules: list[tuple[str, str]]) -> str:
    body = "".join(f"    ({name!r}, {source!r}),\n" for name, source in modules)
    return f"{HEADER}{body})\n"


def main() -> int:
    modules = read_modules()
    TARGET.write_text(render(modules), encoding="utf-8", newline="\n")
    print(f"stdlib: embedded {len(modules)} modules -> {TARGET.relative_to(Path.cwd())}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
